In [128]:
import numpy as np
import scipy.stats as st
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline
import seaborn as sns

In [129]:
df = pd.read_csv("/content/google_play_store_apps_reviews_training.csv")
df.head()

package_name                                             review  \
0  com.facebook.katana   privacy at least put some option appear offli...   
1  com.facebook.katana   messenger issues ever since the last update, ...   
2  com.facebook.katana   profile any time my wife or anybody has more ...   
3  com.facebook.katana   the new features suck for those of us who don...   
4  com.facebook.katana   forced reload on uploading pic on replying co...   

   polarity  
0         0  
1         0  
2         0  
3         0  
4         0

In [130]:
df.shape

(891, 3)

In [131]:
df.groupby('polarity').describe()

package_name                                  review         \
                count unique                  top freq  count unique   
polarity                                                               
0                 584     22  com.facebook.katana   40    584    584   
1                 307     21       com.hamropatro   38    307    307   

                                                                  
                                                        top freq  
polarity                                                          
0          privacy at least put some option appear offli...    1  
1          love it you are able to see celebrity tweets ...    1

In [132]:
df['1']=df['polarity'].apply(lambda x: 1 if x=='1' else 0)
df.head()

package_name                                             review  \
0  com.facebook.katana   privacy at least put some option appear offli...   
1  com.facebook.katana   messenger issues ever since the last update, ...   
2  com.facebook.katana   profile any time my wife or anybody has more ...   
3  com.facebook.katana   the new features suck for those of us who don...   
4  com.facebook.katana   forced reload on uploading pic on replying co...   

   polarity  1  
0         0  0  
1         0  0  
2         0  0  
3         0  0  
4         0  0

In [133]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.review,df.polarity)

In [134]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_count = v.fit_transform(X_train.values)
X_train_count.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [135]:
review = ['Hello my name is james', 'james this is my python notebook', 'james trying to create a big dataset',
'james of words to try differnt', 'features of count vectorizer']
coun_vect = CountVectorizer()
count_matrix = coun_vect.fit_transform(review)
count_array = count_matrix.toarray()
df = pd.DataFrame(data=count_array,columns = coun_vect.get_feature_names())
print(df)

   big  count  create  dataset  differnt  features  hello  is  james  my  \
0    0      0       0        0         0         0      1   1      1   1   
1    0      0       0        0         0         0      0   1      1   1   
2    1      0       1        1         0         0      0   0      1   0   
3    0      0       0        0         1         0      0   0      1   0   
4    0      1       0        0         0         1      0   0      0   0   

   name  notebook  of  python  this  to  try  trying  vectorizer  words  
0     1         0   0       0     0   0    0       0           0      0  
1     0         1   0       1     1   0    0       0           0      0  
2     0         0   0       0     0   1    0       1           0      0  
3     0         0   1       0     0   1    1       0           0      1  
4     0         0   1       0     0   0    0       0           1      0  


/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [136]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_count,y_train)

MultinomialNB()

In [137]:
review = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]
review_count = v.transform(review)
model.predict(review_count)

array([0, 1])

In [138]:
X_test_count = v.transform(X_test)
model.score(X_test_count, y_test)

0.8071748878923767

In [139]:
from sklearn.pipeline import Pipeline
clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [140]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [141]:
clf.score(X_test,y_test)

0.8071748878923767

In [142]:
clf.predict(review)

array([0, 1])